install:
    pip install --upgrade pip &&\
        pip install -r requirements.txt
test:
  python -m pytest general_controller.py
format:
    black *.py

lint:
    pylint --disable=R,C src/cifar10/*.py 


all: install lint test format 